### ISSUE TITLE
.

### ISSUE THREAD

**Issue by azeghers** [ZennerBlade/Movie-Catalog#1]

**Comment by ZennerBlade** [comment]
@azeghers Did it work for you?
I got this working. Let me know if you still need help.

**Comment by azeghers** [comment]
It worked yes, I didn't know how to contact you because I couldn't reply in the thread so I opened this, but then I figured it out. Thanks for checking in and sorry about the clutter.

**Comment by ZennerBlade** [comment]
No issues.
Glad it worked for you too
